'use strict';

const CHAR_TILE = {
  x: Hard,
  w: Lava,
}

const MAPS = [
  [
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxx            xxxx',
    'xxx              xxx',
    'xx                xx',
    'x  xxxx xxxx xxxx  x',
    'x  x    x  x x  x  x',
    'x  xxx  xxx  xxx   x',
    'x     x x  x x  x  x',
    'x  xxxx xxxx xxxx  x',
    'x                  x',
    'x                  x',
    'x                  x',
    'x                  x',
    'x                  x',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
  ],
  [
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxx            xxxx',
    'xxx              xxx',
    'xx                xx',
    'x                  x',
    'x      222222      x',
    'x      111111      x',
    'x                  x',
    'x                  x',
    'x                  x',
    'x                  x',
    'x  xx          xx  x',
    'xx                xx',
    'x                  x',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxx',
  ],
  [
    'xxxxxxxxxxxxxxxxxxxx',
    'xxxxx          xxxxx',
    'xxxx            xxxx',
    'xxx              xxx',
    'xx                xx',
    'x    3333333333    x',
    'x     22222222     x',
    'x      111111      x',
    'x       1111       x',
    'x                  x',
    'x     1 2  2 1     x',
    'w                  w',
    'x        11        x',
    'x                  x',
    'x                  x',
    'x                  x',
    'x                  x',
    'x         111111   x',
    'x                  x',
    'xx                xx',
    'xxx   111111     xxx',
    'xxxx            xxxx',
    'xxxxx          xxxxx',
    'xxxxxxxxwxxxwxxxxxxx',
  ]
]

const MAP_TILES = [
  1,
  6+6,
  10+8+6+4+4+2+6+6,
]
